import Head from 'next/head';
import Layout from '../components/layout/Layout';
import styles from '../styles/Archiv.module.scss';
import InterestedInHelper from '../components/forms/InterestedInHelper';

export default function PageArchiv() {
  return (
    <>
      <Head>
        <title>Archiv projektů</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <p>Archiv projektů</p>
          <InterestedInHelper></InterestedInHelper>
        </main>
      </Layout>
    </>
  );
}
