import Link from 'next/link';
import Head from 'next/head';
import Layout from '../components/layout/Layout';
import styles from '../styles/Page.module.scss';

export default function Helper() {
  return (
    <>
      <Head>
        <title>Chci pomoct</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <p>Hlavní stránka pro ty, kdo chtějí pomáhat</p>
          <p>Seznam dostupných projektů, které potřebují pomoct</p>
          <ul>
            <li>Komponenta projekt</li>
            <li>Komponenta projekt</li>
            <li>Komponenta projekt</li>
          </ul>
          <p>
            <Link href="/new_helper">
              <a>Odkaz na formulář (přidání nového pomocníka)</a>
            </Link>
            , když si nevyberou z projektů
          </p>
        </main>
      </Layout>
    </>
  );
}
