import Link from 'next/link';
import Head from 'next/head';
import Layout from '../components/layout/Layout';
import styles from '../styles/Page.module.scss';
import Project from '../components/projects/Project';
import project_vzor from '../data/project_vzor.json';

export default function Helper() {
  return (
    <>
      <Head>
        <title>Chci pomoct</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <p>Hlavní stránka pro ty, kdo chtějí pomáhat</p>
          <p>Seznam dostupných projektů, které potřebují pomoct</p>
          {project_vzor.map((project) => (
            <Project
              key={project.id}
              businessField={project.businessField}
              name={project.name}
              eactivityDescription={project.eactivityDescription}
              projectPurpose={project.projectPurpose}
              fullname={project.fullname}
              organization={project.organization}
              phonenumber={project.phonenumber}
              email={project.email}
              oldWeb={project.oldWeb}
              links={project.links}
              experiences={project.experiences}
              reward={project.reward}
            ></Project>
          ))}
          <p>
            <Link href="/new_helper">
              <a>Odkaz na formulář (přidání nového pomocníka)</a>
            </Link>
            , když si nevyberou z projektů
          </p>
        </main>
      </Layout>
    </>
  );
}
