import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout/Layout';
import styles from '../styles/Home.module.scss';
import LandingArticle from '../components/landing/LandingArticle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Help to Hope</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={true}>
        <main className={styles.main}>
          <LandingArticle
            title="Potřebuji pomoc"
            text="Poskytujete nezištně pomoc - naději ostatním? Potřebuje vaše naděje být více vidět v online světě?"
            link="/"
            align="left"
          />
          <Image
            src="/img_HtH.png"
            alt="ruka"
            width={1000}
            height={1000}
          ></Image>
          <LandingArticle
            title="Nabízím pomoc"
            text="Chcete pomoci nějaké naději být více vidět v online světě? Pohybujete se v online světě?"
            link="/"
            align="right"
          />
        </main>
      </Layout>
    </>
  );
}
