import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout/Layout';
import styles from '../styles/Page.module.scss';

export default function Projects() {
  return (
    <>
      <Head>
        <title>Potřebuji pomoct</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <p>Hlavní stránka pro ty, kdo hledají pomoc</p>
          <p>Seznam dostupných pomocníků</p>
          <ul>
            <li>Komponenta pomocník</li>
            <li>Komponenta pomocník</li>
            <li>Komponenta pomocník</li>
          </ul>
          <p>
            <Link href="/new_project">
              <a>Odkaz na formulář</a>
            </Link>
            , když si nevyberou z pomocníků
          </p>
        </main>
      </Layout>
    </>
  );
}
