import Head from 'next/head';
import Layout from '../components/layout/Layout';

export default function Faq() {
  return (
    <>
      <Head>
        <title>Tipy a doporučení</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main>
          <p>Tipy a doporučení pro vyplnění formulářů</p>
        </main>
      </Layout>
    </>
  );
}
