import Head from 'next/head';
import Layout from '../components/layout/Layout';

export default function Faq() {
  return (
    <>
      <Head>
        <title>Často kladené dotazy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className="p-8">
          <h1 className="font-title text-green text-5xl">
            Často kladené dotazy, tipy a doporučení pro vyplnění formulářů
          </h1>
          <p> Kolik mě bude stát propojení s projektem nebo pomocníkem? </p>
          <p>
            Vůbec nic! Naším cílem je pomoci ke zviditelnění v online světě
            jednotlivcům, spolkům, organizacím, dobrovolníkům a všem těm, kteří
            nabízejí nezištně pomoc ostatním. Více se můžete dozvědět na stránce{' '}
            <a href="https://www.helptohope.cz/new_project">
              O projektu Help to Hope
            </a>
            .
          </p>
          <p> Proč potřebujete tolik informací? </p>
          <p>
            Všechny informace, které jsou označeny jako povinné, slouží ke
            zdárnému propojení vhodného specialisty v online světě s konkrétním
            projektem. Nepovinné údaje, které nám poskytnete zlepší vaši
            prezentaci a zvýší vaši šanci být propojen s nejvhodnějším
            projektem/pomocníkem. Více o uchovávání informací naleznete na této
            stránce:{' '}
            <a href="https://www.helptohope.cz/gdpr">Soukromí a cookies</a>.{' '}
          </p>
          <p> Jak rychle mě budete moci propojit s projektem/pomocníkem? </p>
          <p>
            Přijatou žádost, která je směřována ke konkrétnímu
            projektu/pomocníkovi zpracujeme během 24h. Nemusíte se obávat,
            potřebné informace k propojení předáme v co nejkratším termínu to
            bude možné. Předány budou pouze potřebné kontaktní údaje.
          </p>
          <p>
            {' '}
            Jak se mohu přidat na web jako nový pomocník v některé z online
            oblastí?{' '}
          </p>
          <p>
            Pokud nenaleznete na{' '}
            <a href="https://www.helptohope.cz/helper">výpisu projektů</a>{' '}
            vyhovující projekt, kterému byste chtěl/-a věnovat své znalosti a
            čas, pak prosím, vyplňte formulář{' '}
            <a href="https://www.helptohope.cz/new_helper">Nový pomocník</a>.
          </p>
          <p> Když se přidám na web jako nový pomocník, co bude následovat? </p>
          <p>
            Vámi vyplněný formulář s požadovanými informacemi zpracujeme v co
            nejkratším čase, zpravidla do 24h. Nový pomocník se zobrazí ve
            výpisu všech, kteří chtějí pomáhat{' '}
            <a href="https://www.helptohope.cz/projects">na této stránce</a>.
          </p>
          <p>
            Jak mohu přidat na web svůj projekt, ke kterému hledám pomocníka?
          </p>
          <p>
            Pokud nenaleznete ve{' '}
            <a href="https://www.helptohope.cz/projects">výpisu pomocníků</a>{' '}
            žádného, který by nabízel služby, které potřebujete, tak neváhejte
            vyplnit formulář
            <a href="https://www.helptohope.cz/new_project"> Nový projekt</a>,
            aby se o něm dozvěděli noví pomocníci.
          </p>
          <p> Když přidám na váš web svůj projekt, co bude následovat? </p>
          <p>
            Vámi vyplněný formulář s požadovanými informacemi zpracujeme v co
            nejkratším čase, zpravidla do 24h. Nový projekt se zobrazí ve výpisu
            všech projektů, které aktuálně hledají pomoc od pomocníka{' '}
            <a href="https://www.helptohope.cz/helper">na této stránce</a>.
          </p>
          <p>
            {' '}
            Uvádíte, že propojení s pomocníkem je zdarma, je možné mu však
            nabídnout odměnu za pomoc s projektem?{' '}
          </p>
          <p>
            Ano, i to je možné! Pokud budete přidávat na náš web svůj projekt,
            pak můžete ve{' '}
            <a href="https://www.helptohope.cz/new_project">formuláři</a> uvést,
            že nabízíte možnou odměnu a nalákat tak pomocníka, kterému se
            zalíbí. Odměna však je nefinančního charakteru v podobě naturálií
            (např. projekt, který potřebuje vytvořit nový web pro farmu nabídne
            bio vajíčka).
          </p>
        </main>
      </Layout>
    </>
  );
}
