import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout/Layout';
import styles from '../styles/Page.module.scss';
import InterestInProject from '../components/forms/InterestInProject';
import { useContext } from 'react';
import { AppContext } from '../libs/appContext';

export default function ProjectInt() {
  const { nameProjectLS } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Vybraný projekt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <h2>Název vybraného projektu: {nameProjectLS}</h2>
          <InterestInProject></InterestInProject>
          <p>
            Pokud si nevíte rady s vyplněním, zkuste se podívat na naše
            <Link href="/faq">
              <a> tipy a doporučení</a>
            </Link>
            , nebo nás
            <Link href="/kontakty">
              <a> kontaktujte</a>
            </Link>
            .
          </p>
        </main>
      </Layout>
    </>
  );
}
