import Head from 'next/head';
import Layout from '../components/layout/Layout';
import ContactForm from '../components/forms/ContactForm';

export default function PageKontakty() {
  return (
    <>
      <Head>
        <title>Kontakt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main>
          <h1>Kontakt</h1>
          <h2>Help to Hope</h2>
          <h3>Blanka Bartoňová</h3>
          <h3> Martina Chromá</h3>

          <p>
            E-mail:{' '}
            <a href="mailto:helptohope.info@gmail.com">
              helptohope.info@gmail.com
            </a>
          </p>
          <p>
            Neváhejte se na nás kdykoliv obrátit. Tým Help to Hope: Blanka &
            Martina
          </p>

          <ContactForm></ContactForm>

          <p>* povinné položky</p>
        </main>
      </Layout>
    </>
  );
}
