import Head from 'next/head';
import Layout from '../components/layout/Layout';
import styles from '../styles/Page.module.scss';
import ContactForm from '../components/forms/ContactForm';

export default function PageKontakty() {
  return (
    <>
      <Head>
        <title>Kontakt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className={styles.main}>
          <h1>Kontakt</h1>

          <ContactForm></ContactForm>
          <p>
            Neváhejte se na nás kdykoliv obrátit. Můžete vyplnit formulář níže
            nebo nás kontaktovat na e-mailu helptohope.info@gmail.com.
          </p>
          <p>Tým Help to Hope: Blanka & Martina :-)</p>
        </main>
      </Layout>
    </>
  );
}
