import Head from 'next/head';
import Layout from '../components/layout/Layout';

export default function successSent() {
  return (
    <>
      <Head>
        <title>Poděkování za odeslání</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main className="p-8 min-h-screen bg-success-backround bg-bottom flex flex-col justify-around">
          <div className="flex flex-col">
            <h1 className="font-title text-green text-5xl">
              Děkujeme za vyplnění a odeslání.
            </h1>
            <h2 className="font-title text-grey text-4xl pt-4">
              Brzy vás budeme kontaktovat.
            </h2>
          </div>
        </main>
      </Layout>
    </>
  );
}
