import Head from 'next/head';
import Layout from '../components/layout/Layout';

export default function successSent() {
  return (
    <>
      <Head>
        <title>Poděkování za odeslání</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout isLandingPage={false}>
        <main>
          <p>Děkujeme za odeslání.</p>
        </main>
      </Layout>
    </>
  );
}
